### ISSUE TITLE
Apple M1 support?

### ISSUE THREAD

**Issue by mattwigway** [JuliaGeo/LibSpatialIndex.jl#15]
Currently, when installing on an M1 Mac using aarch64 julia, you get the following error when creating a spatial index:

`ERROR: UndefVarError: libspatialindex_c not defined`

I believe this is because `LibSpatialIndex_jll` is not built for M1 Macs. Fixing this should be straightforward (and I'm happy to take a stab at it myself), but per JuliaPackaging/Yggsdrasil#2763, this requires increasing the compat entry for `LibSpatialIndex_jll` (and by extension `LibSpatialIndex.jl`) to at least 1.6. Currently `LibSpatialIndex.jl` indicates it is compatible down to Julia 1.0, though I suspect that pre-1.3 won't work well because JLL packages can't be loaded. 1.6 has been the LTS for a while now, would there be objections to dropping support for Julia <= 1.5?

**Comment by visr** [comment]
I don't think requiring julia 1.6 for new versions of this package would be an issue. Would be great if you could take a stab at updating the build.

**Comment by evetion** [comment]
Confirmed working on M1 right now. 🎉
